In [8]:
# M = {11,12,13,14}
M = set ([11,12,12,13,14,15])

# M = set ((11,12,13,14))
# M = set ([11,12],[13,14],[14,15])

M

{11, 12, 13, 14, 15}

In [1]:
tuple = (7,8,9,10,11,12)
print(sum(tuple, 9))

66


In [2]:
7 + 8 + 9 + 10 + 11 + 12 + 9

66

In [3]:
fruit={"apple":"red","guava":"green","grape":"purple"}
len(fruit)

3

In [4]:
x = [7, 8, 9]; 
x.append(44)
print(x)

[7, 8, 9, 44]


In [5]:
tuple=(2,4,6,3,7)
tuple1=(1,2,3)

len(tuple)
tuple + tuple1

(2, 4, 6, 3, 7, 1, 2, 3)

In [1]:
print(range(4))

n = [ x * x for x in range(4)]
n

range(0, 4)


[0, 1, 4, 9]

In [2]:
fruit={"apple":"red","guava":"green","grape":"purple"}

len(fruit)

3

In [7]:
Fruits = ['grapefruit', 'pineapple', 'blueberries', 'mango', 'banana']
Y=Fruits[::3]
print(Y)

['grapefruit', 'mango']


In [4]:
import array as arr
a=arr.array('d',[2.5,3.5,4.5])
a[-1]

4.5

In [12]:
# create a dictionary
d = {'a': 1, 'b': 2, 'c': 3}

d['a']
print(d)
d['d'] = "new"
print(d)
d['d'] = "new1"
print(d)
d.update(d = "new_new")
print(d)    
del d['d']
print(d)
del d
""" results in a NameError: name 'd' is not defined """
# print(d) 

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 'new'}
{'a': 1, 'b': 2, 'c': 3, 'd': 'new1'}
{'a': 1, 'b': 2, 'c': 3, 'd': 'new_new'}
{'a': 1, 'b': 2, 'c': 3}


" results in a NameError: name 'd' is not defined "

In [30]:
# create an array
a = [1, 2, 3, "new", "new_new"]
a.append(33)
print(a)
a.pop()
print(a)
a.pop()
print(a)
a.insert(3,4)
print(a)
a.remove(4)
print(a)
a.reverse()
print(a)
# a.sort()
# print(a)

[1, 2, 3, 'new', 'new_new', 33]
[1, 2, 3, 'new', 'new_new']
[1, 2, 3, 'new']
[1, 2, 3, 4, 'new']
[1, 2, 3, 'new']
['new', 3, 2, 1]


In [37]:
# create a tuple
t = (1, 2, 3, "new", "new_new")

print(t)
""" slice(stop) slice(start, stop[, step]) """
t[slice(0,4, 3)]

(1, 2, 3, 'new', 'new_new')


(1, 'new')

In [50]:
# create a set
s = {1, 3, "new", "new_new"}
s1 = {1, 2, 2, 3, "new", "new_new", "new_new"}
# print(s)
# print(s1)
s.add(4)
print(s)
i = s.union(s1)
print(i)
j = s.intersection(s1)
print(j)

{1, 3, 4, 'new', 'new_new'}
{1, 2, 3, 4, 'new', 'new_new'}
{1, 3, 'new_new', 'new'}


In [52]:
!! pip install numpy
!! pip install pandas 

['Requirement already satisfied: pandas in /home/novasangeeth/work/pytest-workouts/env/lib/python3.9/site-packages (1.4.1)',
 'Requirement already satisfied: pytz>=2020.1 in /home/novasangeeth/work/pytest-workouts/env/lib/python3.9/site-packages (from pandas) (2022.1)',
 'Requirement already satisfied: python-dateutil>=2.8.1 in /home/novasangeeth/work/pytest-workouts/env/lib/python3.9/site-packages (from pandas) (2.8.2)',
 'Requirement already satisfied: numpy>=1.18.5 in /home/novasangeeth/work/pytest-workouts/env/lib/python3.9/site-packages (from pandas) (1.22.3)',
 'Requirement already satisfied: six>=1.5 in /home/novasangeeth/work/pytest-workouts/env/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)']

In [76]:
import numpy as np

a = [1,2,3,4,5,6]
b = [7,8,9,10,11,12]
a_np = np.array(a)
print(a_np)
b_np = np.array(b)
print(b_np)
# create a multi diemensional numpy array.
c = np.array([a,b])
# sum of the columns in the array
print(f"sum of the columns in the array: {c.sum(axis=0)}")
# c.sum(axis=1)
print(f"sum of the rows in the array: {c.sum(axis=1)}")
c.dot(a_np)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
sum of the columns in the array: [ 8 10 12 14 16 18]
sum of the rows in the array: [21 57]


array([ 91, 217])