In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy
from scipy.stats import ttest_1samp
from scipy.stats import ttest_ind
from scipy.stats import t
from scipy.stats import f
from scipy.stats import norm
from statsmodels.stats.proportion import proportions_ztest


In [20]:
# python function to find the rank of the matrix
def rank(A):
    A = np.array(A)
    h, w = A.shape
    for i in range(h):
        if np.all(A[i:, i] == 0):
            A = np.delete(A, i, 0)
            A = np.delete(A, i, 1)
            h -= 1
    return h

    # 2 * 2 matrix
A = [[4, 5, 16, 7], [2, -3, 2, 3], [3, 4, 5, 6], [4, 7, 8, 9]]

rank(A)


4

In [4]:
# the determinant of a matrix.
Z = [[-2, 32, 24], [92, 66, 25], [-80, 37, 10]]
np.linalg.det(Z)


115506.00000000006

In [5]:
# inverse of a matrix
P = [[2, 1, 2], [1, 0, 1], [3, 1, 3]]
# function to find the inverse of a matrix


def inverse(A):
    A = np.array(A)
    h, w = A.shape
    if h != w:
        raise ValueError("Matrix must be square")
    if np.linalg.det(A) == 0:
        raise ValueError("Matrix must be non-singular")
    return np.linalg.inv(A)


inverse(
    A
)


array([[ 9.37500000e-02, -4.68750000e-01,  3.68750000e+00,
        -2.37500000e+00],
       [ 1.00929366e-16, -2.50000000e-01,  5.00000000e-01,
        -2.50000000e-01],
       [ 9.37500000e-02,  3.12500000e-02, -3.12500000e-01,
         1.25000000e-01],
       [-1.25000000e-01,  3.75000000e-01, -1.75000000e+00,
         1.25000000e+00]])

In [6]:
# function to calculate the eigen values of the given matrix
def eigen_values(A):
    A = np.array(A)
    h, w = A.shape
    if h != w:
        raise ValueError("Matrix must be square")
    return np.linalg.eig(A)[0]


A = [[2, 0, 0], [0, 1, 0], [0, 0, 3]]
sum(eigen_values(A))


B = [[1, 6, 1], [1, 2, 3], [0, 0, 3]]
eigen_values(B)


array([-1.,  4.,  3.])

In [7]:
# function to calculate the distance between two  vectors
def distance(A, B):
    A = np.array(A)
    B = np.array(B)
    return np.linalg.norm(A - B)


V = [8, 9, 2]
V1 = [7, 7, 1]

distance(
    V1,
    V
)


2.449489742783178

In [5]:
# function to multipy two matrices
def multiply(A, B):
    A = np.array(A)
    B = np.array(B)
    return A @ B


A = [
    [1, 0, -1, 2],
    [0, 3, 1, -1],
    [2, 4, 0, 3],
    [-3, 1, -1, 2]
]

B = [
    [1, 2],
    [3, -1],
    [0, -1],
    [4, 2]
]

C = [
    [3, 8, 0, 5],
    [1, 0, -4, 8]
]

CA = [[-12,  29,   0,   8],
      [-31,  -8,  -9,   6]]

multiply(
    A=CA,
    B=B
)


array([[107, -37],
       [-31, -33]])

In [13]:
# inverse of a matrix:
P = [[2, 1, 2], [1, 0, 1], [3, 1, 3]]

# function to find the inverse of a matrix


def inverse(A):
    A = np.array(A)
    h, w = A.shape
    if h != w:
        raise ValueError("Matrix must be square")
    if np.linalg.det(A) == 0:
        raise ValueError("Matrix must be non-singular")
    return np.linalg.inv(A)


# inverse(
#     A=P
# )

np.linalg.det(P)


0.0

In [18]:
# two orothogonal vectors
V = [5, -2, 3]
V1 = [-2, 4, 6]

# find if two vectors are orthogonal


def orthogonal(A, B):
    A = np.array(A)
    B = np.array(B)
    return np.allclose(A @ B, 0)


orthogonal(
    A=V,
    B=V1
)


True

In [25]:
# The matrix from AX=B

A = [
    [4, -2, 6],
    [1, 1, -3],
    [15, -3, 9]
]
B = [
    ['x', 'y', 'z']
]

C = [
    [8, -1, 21]
]


rank_a = 3
rank_b = 1
rank_c = 1

rank(C)
# multiply(
#     A=A,
#     B=B
# )


1